version: '3.1'
services:
  #################################
  #  Main app container           #
  #################################
  app:
    volumes:
      -  ".:/srv/app"
      -  "~/.composer:/root/.composer"
      -  ".service-main/.php/php.user.ini:/usr/local/etc/php/conf.d/php.user.ini"
    command: bash -c "./start.sh" # run initial tasks
    working_dir: "/srv/app"