version: '3.1'
services:
  #################################
  #  Main app container           #
  #################################
  app:
    image: webmagicagency/laravel6.x_php7.3_apache # minimal