version: '3.1'
services:
  #################################
  #  Main app container           #
  #################################
  app:
    #    build:
    #      context: .
    #      dockerfile: .docker/local/Dockerfile
    #    image: webmagicagency/laravel6.x_php7.3_apache # minimal
    image: webmagicagency/laravel6.x_php7.3_apache_node12 # for front-end
    ports:
      - "8080:80"
    volumes:
      -  "../packages:/srv/packages"

  #################################
  #  Database container           #
  #################################
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      -  ".mysql:/var/lib/mysql"